### ISSUE TITLE
Student Learning Dashboard Design

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#123]
The goal is to design a modified learning tab for the student users so that they can see:

- [ ] Class Info in their overview (issue #124)
- [ ] Assignments tab with a matrix and calendar view (issue #125)
- [ ] Activity Log (same as what we already have)
- [ ] And practice log (from issue #118)
